### ISSUE TITLE
babel-runtime

### ISSUE THREAD

**Issue by palavrov** [mgtitimoli/await-mutex#3]
The module lacks `babel-runtime` runtime dependency as it is suggested when using `transform-runtime` plugin.

https://babeljs.io/docs/plugins/transform-runtime/#installation

https://babeljs.io/docs/plugins/transform-runtime/#technical-details

**Comment by mgtitimoli** [comment]
It is listed as dev-dependency and it should have been declared as a normal one, this is why you are getting an issue.

I will push a new release with the fix, thanks for having taken the time to report the issue.

**Comment by palavrov** [comment]
That is the problem, it should be a normal dependency.

Just don't ask me how much time it cost me to dig who miss to include it causing my app to miserably fail - on my dev machine everything was OK but not in the production ;)

**Comment by mgtitimoli** [comment]
Sorry to hear that @palavrov, and apologies for the issue, I'm about to release a new version which it will also include a fix for #1, and other fixes I found in the way.
